"use strict"

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("artists", [
      {
        user_id: 1,
        name: "Drake",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 2,
        name: "Billie Eilish",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 3,
        name: "The Weeknd",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 4,
        name: "The Beatles",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 5,
        name: "Metallica",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 6,
        name: "Twice",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 7,
        name: "Britney Spears",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 8,
        name: "Adele",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 9,
        name: "Ghost",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 10,
        name: "Beethoven",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 11,
        name: "The Clash",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 12,
        name: "James Brown",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 13,
        name: "Brian Eno",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 14,
        name: "deadmau5",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 15,
        name: "Kendrick Lamar",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 16,
        name: "John Coltrane",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 17,
        name: "Black Flag",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 18,
        name: "Boards of Canada",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 19,
        name: "Bob Marley",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 20,
        name: "Bad Bunny",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 21,
        name: "BTS",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 22,
        name: "ITZY",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 23,
        name: "The Weeknd",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 24,
        name: "John Legend",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 25,
        name: "Alicia Keys",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 26,
        name: "The Weeknd",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 27,
        name: "TOOL",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 28,
        name: "Johnny Cash",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 29,
        name: "Simon & Garfunkel",
        liked: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 30,
        name: "Black Sabbath",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        user_id: 31,
        name: "Two Door Cinema Club",
        liked: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("artists")
  },
}
