"use strict"

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          name: "Justin Harris",
          email: "jharris@gmail.com",
          password: "admin1",
          photo: "https://imgur.com/ttaOi6C.jpg",
          genreInterest: "Punk",
          artistInterest: "The Clash",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Matt Sweeney",
          email: "msweeney@gmail.com",
          password: "admin2",
          photo: "https://imgur.com/UgtSNzz.jpg",
          genreInterest: "Pop",
          artistInterest: "Billie Eilish",
          liked: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jack Viana",
          email: "jviana@gmail.com",
          password: "admin3",
          photo: "https://imgur.com/j5cmgCe.jpg",
          genreInterest: "K-Pop",
          artistInterest: "Twice",
          liked: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jordan Wolter",
          email: "email1@email.com",
          password: "admin4",
          photo: "https://imgur.com/fqIK3zq.jpg",
          genreInterest: "EDM",
          artistInterest: "Kaskade",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jeremy Taubman",
          email: "email2@email.com",
          password: "admin5",
          photo: "https://imgur.com/kPeYEzt.jpg",
          genreInterest: "Rock",
          artistInterest: "The Beatles",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Devon Jones",
          email: "email3@email.com",
          password: "admin6",
          photo: "https://imgur.com/fMvbSbq.jpg",
          genreInterest: "Metal",
          artistInterest: "Metallica",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tylus Dawkins",
          email: "",
          password: "admin7",
          photo: "https://i.imgur.com/GsE7PtU.jpg",
          genreInterest: "Rock",
          artistInterest: "Two Door Cinema Club",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tim Villanueva",
          email: "email4@email.com",
          password: "admin8",
          photo: "https://i.imgur.com/GsE7PtU.jpg",
          genreInterest: "Jazz",
          artistInterest: "John Coltrane",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Greg Swan",
          password: "admin9",
          email: "email5@email.com",
          photo: "https://imgur.com/YFwvsGk.jpg",
          genreInterest: "Folk",
          artistInterest: "Simon & Garfunkel",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Lindsey Lawler",
          email: "email6@email.com",
          password: "admin10",
          photo: "https://imgur.com/xfjbHdY.jpg",
          genreInterest: "Country",
          artistInterest: "Johnny Cash",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Imdad Hassain",
          email: "email7@email.com",
          password: "admin11",
          photo: "https://imgur.com/LfImSU3.jpg",
          genreInterest: "EDM",
          artistInterest: "deadmau5",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Andrew Zheng",
          email: "email8@email.com",
          password: "admin12",
          photo: "https://imgur.com/NNm5vjb.jpg",
          genreInterest: "Metal",
          artistInterest: "Ghost",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tyler Wade",
          email: "email9@email.com",
          password: "admin13",
          photo: "https://imgur.com/rXxW0wv.jpg",
          genreInterest: "Rap",
          artistInterest: "Kendrick Lamar",
          liked: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Brandon Chan",
          email: "email10@email.com",
          password: "admin15",
          photo: "https://imgur.com/tGQjioL.jpg",
          genreInterest: "Ambient",
          artistInterest: "Brian Eno",
          liked: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Jeremy Villavla",
          email: "email11@email.com",
          password: "admin16",
          photo: "https://imgur.com/LsLS8Gv.jpg",
          genreInterest: "Funk",
          artistInterest: "James Brown",
          liked: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    )
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("users")
  },
}
